// Mock/seed data for EcoWeave dashboard demo

import type { BatchRecord } from './types';

export const seedBatches: BatchRecord[] = [
  {
    batch_id: 'B-2401',
    shift_date: '2026-02-10',
    shift_name: 'Night Shift A',
    production_volume_kg: 850,
    chemical_usage_kg: 72,
    etp_runtime_min: 0, // Bypass scenario
    electricity_kwh: 95,
    chemical_invoice_bdt: 57600,
    etp_cost_bdt: 15000,
    notes: 'High production night shift',
  },
  {
    batch_id: 'B-2402',
    shift_date: '2026-02-10',
    shift_name: 'Day Shift B',
    production_volume_kg: 650,
    chemical_usage_kg: 48,
    etp_runtime_min: 85,
    electricity_kwh: 92,
    chemical_invoice_bdt: 38400,
    etp_cost_bdt: 12000,
    notes: 'Normal operation',
  },
  {
    batch_id: 'B-2403',
    shift_date: '2026-02-11',
    shift_name: 'Night Shift B',
    production_volume_kg: 920,
    chemical_usage_kg: 88,
    etp_runtime_min: 15, // Insufficient treatment
    electricity_kwh: 98,
    chemical_invoice_bdt: 70400,
    etp_cost_bdt: 15000,
    notes: 'Rush order - expedited',
  },
  {
    batch_id: 'B-2404',
    shift_date: '2026-02-11',
    shift_name: 'Day Shift A',
    production_volume_kg: 420,
    chemical_usage_kg: 32,
    etp_runtime_min: 65,
    electricity_kwh: 68,
    chemical_invoice_bdt: 25600,
    etp_cost_bdt: 10000,
    notes: 'Standard batch',
  },
  {
    batch_id: 'B-2405',
    shift_date: '2026-02-12',
    shift_name: 'Morning Shift',
    production_volume_kg: 780,
    chemical_usage_kg: 65,
    etp_runtime_min: 25, // Low treatment time
    electricity_kwh: 82,
    chemical_invoice_bdt: 52000,
    etp_cost_bdt: 14000,
    notes: 'Equipment maintenance completed',
  },
  {
    batch_id: 'B-2406',
    shift_date: '2026-02-12',
    shift_name: 'Evening Shift',
    production_volume_kg: 540,
    chemical_usage_kg: 41,
    etp_runtime_min: 78,
    electricity_kwh: 76,
    chemical_invoice_bdt: 32800,
    etp_cost_bdt: 11000,
    notes: 'Normal operation',
  },
  {
    batch_id: 'B-2407',
    shift_date: '2026-02-13',
    shift_name: 'Night Shift A',
    production_volume_kg: 890,
    chemical_usage_kg: 0, // Missing data
    etp_runtime_min: 0,
    electricity_kwh: 45, // Power anomaly
    chemical_invoice_bdt: 0,
    etp_cost_bdt: 15000,
    notes: 'Data collection issues reported',
  },
  {
    batch_id: 'B-2408',
    shift_date: '2026-02-13',
    shift_name: 'Day Shift B',
    production_volume_kg: 610,
    chemical_usage_kg: 46,
    etp_runtime_min: 82,
    electricity_kwh: 88,
    chemical_invoice_bdt: 36800,
    etp_cost_bdt: 12500,
    notes: 'Regular production',
  },
  {
    batch_id: 'B-2409',
    shift_date: '2026-02-14',
    shift_name: 'Morning Shift',
    production_volume_kg: 720,
    chemical_usage_kg: 58,
    etp_runtime_min: 90,
    electricity_kwh: 102,
    chemical_invoice_bdt: 46400,
    etp_cost_bdt: 13000,
    notes: 'Full compliance',
  },
  {
    batch_id: 'B-2410',
    shift_date: '2026-02-14',
    shift_name: 'Day Shift A',
    production_volume_kg: 950,
    chemical_usage_kg: 95,
    etp_runtime_min: 12, // Very low treatment
    electricity_kwh: 105,
    chemical_invoice_bdt: 25000, // Invoice mismatch (too low)
    etp_cost_bdt: 16000,
    notes: 'Urgent export order',
  },
  {
    batch_id: 'B-2411',
    shift_date: '2026-02-14',
    shift_name: 'Evening Shift',
    production_volume_kg: 380,
    chemical_usage_kg: 28,
    etp_runtime_min: 55,
    electricity_kwh: 58,
    chemical_invoice_bdt: 22400,
    etp_cost_bdt: 9500,
    notes: 'Small batch',
  },
  {
    batch_id: 'B-2412',
    shift_date: '2026-02-14',
    shift_name: 'Night Shift B',
    production_volume_kg: 810,
    chemical_usage_kg: 68,
    etp_runtime_min: 0, // Another bypass
    electricity_kwh: 88,
    chemical_invoice_bdt: 54400,
    etp_cost_bdt: 14500,
    notes: 'Night production spike',
  },
];
